# Generated by Django 4.1.3 on 2022-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'разное'), ('food', 'еда'), ('drinks', 'напитки')], default='other', max_length=30, verbose_name='Категория товара'),
        ),
    ]
